<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/bwalk/Documents/bradleywalkernet/residual_vr1.glb
-->

<script>
  import { Group, FrontSide } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('https://zsbqtqognaiogrpqaoot.supabase.co/storage/v1/object/public/art-records/residual_vr1.glb')

  const component = forwardEventHandlers()
  // Modify materials to be single-sided when loaded
  $: if ($gltf) {
    Object.values($gltf.materials).forEach(material => {
      material.side = FrontSide;
    });
  }
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0.13, -0.01, 0]}>
      <T.Mesh geometry={gltf.nodes.Cube061.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Cube061_1.geometry} material={gltf.materials.light} />
      <T.Mesh geometry={gltf.nodes.Cube061_2.geometry} material={gltf.materials.plastic} />
      <T.Mesh geometry={gltf.nodes.Cube061_3.geometry} material={gltf.materials['light.001']} />
      <T.Mesh geometry={gltf.nodes.Cube061_4.geometry} material={gltf.materials.steel} />
      <T.Mesh geometry={gltf.nodes.Cube061_5.geometry} material={gltf.materials.wall} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
